# German translations for vigilo-correlator.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-correlator
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-correlator 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 12:29+0100\n"
"PO-Revision-Date: 2011-05-06 15:43+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_correlator.py:36
msgid "The topology has been reloaded."
msgstr "Die Topologie wurde erneut geladen."

#: src/twisted/plugins/vigilo_correlator.py:53
msgid ""
"Could not set signal handlers. The correlator may not be able to shutdown"
" cleanly"
msgstr ""
"Signalhandler konnte nicht eingestellt werden. Es kann sein, dass der "
"Korrelator nicht sauber herunterfahren kann"

#: src/vigilo/correlator/correvent.py:116
#, python-format
msgid "Updating existing correlated event (%r)"
msgstr "Bestehendes korreliertes Ereignis (%r) aktualisieren"

#: src/vigilo/correlator/correvent.py:119
#, python-format
msgid "Got a reference to a non-existent correlated event (%r), adding as new"
msgstr ""
"Verweis auf ein nicht vorhandenes korreliertes Ereignis (%r), wird als "
"neu hinzugefügt"

#: src/vigilo/correlator/correvent.py:129
#, python-format
msgid "Raw event ignored. Reason: status = %r"
msgstr "Rohereignis ignoriert. Ursache: Status = %r"

#: src/vigilo/correlator/correvent.py:155
#, python-format
msgid ""
"Got a reference to a nonexistent correlated event (%r), skipping this "
"aggregate"
msgstr ""
"Verweis auf ein nicht vorhandenes korreliertes Ereignis (%r), Aggregat "
"wird übersprungen"

#: src/vigilo/correlator/correvent.py:198
msgid "Creating new correlated event"
msgstr "Neues korreliertes Ereignis wird erstellt"

#: src/vigilo/correlator/correvent.py:313
msgid "Sending correlated event to syslog"
msgstr "Korreliertes Ereignis wird an Syslog gesendet"

#: src/vigilo/correlator/db_insertion.py:47
#, python-format
msgid "Received request to add an event on HLS \"%s\""
msgstr "Anforderung zur Hinzufügung eines Ereignisses auf HLS \"%s\" erhalten"

#: src/vigilo/correlator/db_insertion.py:55
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), "
"skipping event"
msgstr ""
"Verweis auf ein nicht konfiguriertes Element (%(host)r, %(service)r) "
"erhalten, Ereignis übersprungen"

#: src/vigilo/correlator/db_insertion.py:87
#, python-format
msgid "Updating event %r"
msgstr "Ereignis %r wird aktualisiert"

#: src/vigilo/correlator/db_insertion.py:93
#, python-format
msgid ""
"Ignoring request to create a new event with state \"%s\" (nothing "
"alarming here)"
msgstr ""
"Anforderung zur Erstellung eines neuen Ereignisse mit Status \"%s\" wird "
"ignoriert (hier nicht bedenklich)"

#: src/vigilo/correlator/db_insertion.py:100
msgid "Creating new event"
msgstr "Neues Ereignis wird erstellt"

#: src/vigilo/correlator/db_insertion.py:103
msgid "Multiple matching events found, skipping."
msgstr "Mehrere entsprechende Ereignisse gefunden, überspringen."

#: src/vigilo/correlator/db_insertion.py:148
#: src/vigilo/correlator/db_insertion.py:183
#: src/vigilo/correlator/db_insertion.py:227
#: src/vigilo/correlator/db_insertion.py:247
msgid "Got exception"
msgstr "Ausnahme vorhanden"

#: src/vigilo/correlator/db_insertion.py:168
#, python-format
msgid "Got a reference to a non configured high-level service (%(service)r)"
msgstr ""
"Verweis auf einen nicht konfigurierten High-level-Service (%(service)r) "
"vorhanden"

#: src/vigilo/correlator/db_insertion.py:201
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), "
"skipping state"
msgstr ""
"Verweis auf ein nicht konfiguriertes Element (%(host)r, %(service)r) "
"vorhanden, Status überspringen"

#: src/vigilo/correlator/db_insertion.py:264
#, python-format
msgid "Merging aggregate #%(src)d with aggregate #%(dest)d"
msgstr "Aggregat #%(src)d und Aggregat #%(dest)d werden zusammengeführt"

#: src/vigilo/correlator/db_insertion.py:275
msgid ""
"merge_aggregates: Got a reference to a nonexistent source aggregate, "
"aborting"
msgstr ""
"merge_aggregates: Verweis auf ein nicht existierendes Quell-Aggregat "
"vorhanden, abbrechen"

#: src/vigilo/correlator/db_insertion.py:285
#, python-format
msgid ""
"merge_aggregates: Got a reference to a nonexistent destination aggregate "
"%r, aborting"
msgstr ""
"merge_aggregates: Verweis auf ein nicht existierendes Ziel-Aggregat %r "
"vorhanden, abbrechen"

#: src/vigilo/correlator/handle_ticket.py:35
#, python-format
msgid ""
"handle_ticket: Trouble ticket message received. Timestamp = "
"%(timestamp)r. Impacted HLS = %(hls)r. Ticket id = %(ticket_id)r. "
"acknowledgement_status = %(ack_status)r. Message = %(message)r."
msgstr ""
"handle_ticket: Trouble-Ticket-Nachricht erhalten. Timestamp = "
"%(timestamp)r. Betroffene HLS = %(hls)r. Ticket id = %(ticket_id)r. "
"acknowledgement_status = %(ack_status)r. Nachricht = %(message)r."

#: src/vigilo/correlator/handle_ticket.py:57
#, python-format
msgid "handle_ticket: No matching trouble ticket found : %r"
msgstr "handle_ticket: Kein passendes Trouble Ticket gefunden: %r"

#: src/vigilo/correlator/handle_ticket.py:63
#, python-format
msgid "handle_ticket: Several events seem to be associated with this ticket : %r"
msgstr ""
"handle_ticket: Mehrere Ereignisse scheinen zu diesem Ticket : %r zu "
"gehören"

#: src/vigilo/correlator/handle_ticket.py:66
#, python-format
msgid ""
"handle_ticket: The event %(event_id)r is associated with the given ticket"
" (%(ticket_id)r)"
msgstr ""
"handle_ticket: Das Ereignis %(event_id)r gehört zu dem gegebenen Ticket "
"(%(ticket_id)r)"

#: src/vigilo/correlator/handle_ticket.py:88
#, python-format
msgid "handle_ticket: Got exception while updating event %r history"
msgstr ""
"handle_ticket: Ausnahme bei der Aktualisierung des Verlaufs des "
"Ereignisses %r "

#: src/vigilo/correlator/handle_ticket.py:92
#, python-format
msgid "handle_ticket: Event %r history updated successfully."
msgstr "handle_ticket: Verlauf des Ereignisses %r erfolgreich aktualisiert."

#: src/vigilo/correlator/memcached_connection.py:105
#, python-format
msgid "Deleted %(nb_deleted)d expired correlation contexts"
msgstr "Gelöschte %(nb_deleted)d abgelaufene Korrelationskontexte"

#: src/vigilo/correlator/memcached_connection.py:148
#, python-format
msgid "Establishing connection to MemcacheD server (%s)..."
msgstr "Verbindung zum MemcacheD Server (%s) wird hergestellt..."

#: src/vigilo/correlator/memcached_connection.py:167
#, python-format
msgid "Trying to set value '%(value)s' for key '%(key)s'."
msgstr "Versucht den Wert '%(value)s' für Schlüssel '%(key)s' einzustellen."

#: src/vigilo/correlator/memcached_connection.py:217
#, python-format
msgid "Trying to get the value of the key '%(key)s'."
msgstr "Versucht, den Wert von Schlüssel '%(key)s' zu erhalten."

#: src/vigilo/correlator/memcached_connection.py:270
#, python-format
msgid "Trying to delete the key '%(key)s'."
msgstr "Versucht, den Schlüssel '%(key)s' zu löschen."

#: src/vigilo/correlator/registry.py:58
#, python-format
msgid ""
"Rule %(name)s (%(class)s) has already been registered, ignoring attempt "
"to re-register it."
msgstr ""
"Regel %(name)s (%(class)s) wurde bereits registriert, der Versuch, sie "
"erneut zu registrieren, wird ignoriert."

#: src/vigilo/correlator/registry.py:67
#, python-format
msgid "The rule %(depended)r must be loaded before %(dependent)r."
msgstr "Regel %(depended)r muss vor %(dependent)r geladen werden."

#: src/vigilo/correlator/registry.py:75
#, python-format
msgid "Successfully registered rule %r"
msgstr "Erfolgreich registrierte Regel %r"

#: src/vigilo/correlator/registry.py:140
msgid ""
"Singleton has already been instanciated, ignoring attempt to create a new"
" instance."
msgstr ""
"Singleton wurde bereits instanziiert, der Versuch eine neue Instanz zu "
"erstellen wird ignoriert."

#: src/vigilo/correlator/registry.py:175
#, python-format
msgid "Not a valid rule name \"%s\""
msgstr "Nicht ein gültiger Regelname \"%s\""

#: src/vigilo/correlator/registry.py:181
#, python-format
msgid "Unable to load rule \"%(name)s\" (%(class)s)"
msgstr "Unfähig, die Regel \"%(name)s\" (%(class)s) zu laden"

#: src/vigilo/correlator/actors/rule_dispatcher.py:115
msgid ""
"No information from Vigiconf concerning the topology's last modification "
"date. Therefore the topology has NOT been rebuilt."
msgstr ""
"Keine Information von Vigiconf über das letzte Änderungsdatum der "
"Topologie. Deshalb wurde die Topologie NICHT erneut erstellt."

#: src/vigilo/correlator/actors/rule_dispatcher.py:127
msgid "Topology has been reloaded."
msgstr "Topologie wurde erneut geladen."

#: src/vigilo/correlator/actors/rule_dispatcher.py:144
#, python-format
msgid "Sending this payload to the XMPP bus: %r"
msgstr "Senden dieser Nutzlast auf den XMPP Bus: %r"

#: src/vigilo/correlator/actors/rule_dispatcher.py:150
#, python-format
msgid ""
"Registering post-correlation callback function \"%(fn)s\" for alert with "
"ID %(id)s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:260
#, python-format
msgid "Rule %(rule_name)s timed out"
msgstr "Regel %(rule_name)s abgelaufen"

#: src/vigilo/correlator/actors/rule_dispatcher.py:322
#, python-format
msgid "Skipping unrecognized item (%s)"
msgstr "Unbekanntes Element (%s) wird übersprungen"

#: src/vigilo/correlator/actors/rule_dispatcher.py:366
msgid ""
"Error while saving the correlated event. The message will be handled once"
" more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:381
msgid "Received invalid XMPP item ID (None)"
msgstr "Ungültige XMPP Element ID (None) erhalten"

#: src/vigilo/correlator/actors/rule_dispatcher.py:433
msgid ""
"Error while retrieving the network's topology. The message will be "
"handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:448
msgid ""
"Error while adding an entry in the HLS history. The message will be "
"handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:460
msgid ""
"Error while adding an entry in the history. The message will be handled "
"once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:473
msgid "Error while saving state. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:495
#, python-format
msgid "Correlation failed for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:503
#, python-format
msgid "Unable to store correlated alert for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:550
msgid "Connection lost"
msgstr "Verbindung verloren"

#: src/vigilo/correlator/actors/rule_runner.py:82
#, python-format
msgid ""
"Got an exception while running rule %(rule)s. Running the correlator in "
"the foreground (%(prog)s -n) may help troubleshooting"
msgstr ""
"Ausnahme während der Ausführung der Regel %(rule)s. Ausführen der "
"Korrelator im Vordergrund (%(prog)s -n) kann Problemlösungen helfen"

#: src/vigilo/correlator/rules/example.py:36
#, python-format
msgid "id %(id)s payload %(payload)s"
msgstr "id %(id)s Nutzlast %(payload)s"

#: src/vigilo/correlator/test/test_logging.py:268
msgid "Received 'WARNING' message on lls1"
msgstr ""

#: src/vigilo/correlator/test/test_logging.py:289
msgid "Received 'CRITICAL' message on lls1"
msgstr ""

