# Translations template for vigilo-correlator.
# Copyright (C) 2011 ORGANIZATION
# This file is distributed under the same license as the vigilo-correlator
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-correlator 2.0.1\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2011-05-27 14:40+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_correlator.py:36
msgid "The topology has been reloaded."
msgstr ""

#: src/twisted/plugins/vigilo_correlator.py:53
msgid ""
"Could not set signal handlers. The correlator may not be able to shutdown "
"cleanly"
msgstr ""

#: src/vigilo/correlator/correvent.py:83
#, python-format
msgid ""
"Ignoring event #%(idevent)d on (%(host)r, %(service)r) as requested by the "
"correlation rules"
msgstr ""

#: src/vigilo/correlator/correvent.py:130
#, python-format
msgid "Updating existing correlated event (%r)"
msgstr ""

#: src/vigilo/correlator/correvent.py:133
#, python-format
msgid "Got a reference to a non-existent correlated event (%r), adding as new"
msgstr ""

#: src/vigilo/correlator/correvent.py:143
#, python-format
msgid "Raw event ignored. Reason: status = %r"
msgstr ""

#: src/vigilo/correlator/correvent.py:169
#, python-format
msgid ""
"Got a reference to a nonexistent correlated event (%r), skipping this "
"aggregate"
msgstr ""

#: src/vigilo/correlator/correvent.py:212
msgid "Creating new correlated event"
msgstr ""

#: src/vigilo/correlator/correvent.py:328
msgid "Sending correlated event to syslog"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:49
#, python-format
msgid "Received request to add an event on HLS \"%s\""
msgstr ""

#: src/vigilo/correlator/db_insertion.py:57
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), skipping "
"event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:89
#, python-format
msgid "Updating event %r"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:95
#, python-format
msgid ""
"Ignoring request to create a new event with state \"%s\" (nothing alarming "
"here)"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:102
msgid "Creating new event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:105
msgid "Multiple matching events found, skipping."
msgstr ""

#: src/vigilo/correlator/db_insertion.py:150
#: src/vigilo/correlator/db_insertion.py:187
#: src/vigilo/correlator/db_insertion.py:231
#: src/vigilo/correlator/db_insertion.py:251
msgid "Got exception"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:170
#, python-format
msgid "Got a reference to a non configured high-level service (%(service)r)"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:205
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), skipping "
"state"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:268
#, python-format
msgid "Merging aggregate #%(src)d with aggregate #%(dest)d"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:279
msgid "merge_aggregates: Got a reference to a nonexistent source aggregate, aborting"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:289
#, python-format
msgid ""
"merge_aggregates: Got a reference to a nonexistent destination aggregate %r, "
"aborting"
msgstr ""

#: src/vigilo/correlator/db_wrapper.py:58
msgid "The connection with the database was invalidated. Reconnecting..."
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:35
#, python-format
msgid ""
"handle_ticket: Trouble ticket message received. Timestamp = %(timestamp)r. "
"Impacted HLS = %(hls)r. Ticket id = %(ticket_id)r. acknowledgement_status = "
"%(ack_status)r. Message = %(message)r."
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:57
#, python-format
msgid "handle_ticket: No matching trouble ticket found : %r"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:63
#, python-format
msgid "handle_ticket: Several events seem to be associated with this ticket : %r"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:66
#, python-format
msgid ""
"handle_ticket: The event %(event_id)r is associated with the given ticket "
"(%(ticket_id)r)"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:88
#, python-format
msgid "handle_ticket: Got exception while updating event %r history"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:92
#, python-format
msgid "handle_ticket: Event %r history updated successfully."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:105
#, python-format
msgid "Deleted %(nb_deleted)d expired correlation contexts"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:148
#, python-format
msgid "Establishing connection to MemcacheD server (%s)..."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:167
#, python-format
msgid "Trying to set value '%(value)s' for key '%(key)s'."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:217
#, python-format
msgid "Trying to get the value of the key '%(key)s'."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:270
#, python-format
msgid "Trying to delete the key '%(key)s'."
msgstr ""

#: src/vigilo/correlator/registry.py:58
#, python-format
msgid ""
"Rule %(name)s (%(class)s) has already been registered, ignoring attempt to "
"re-register it."
msgstr ""

#: src/vigilo/correlator/registry.py:67
#, python-format
msgid "The rule %(depended)r must be loaded before %(dependent)r."
msgstr ""

#: src/vigilo/correlator/registry.py:75
#, python-format
msgid "Successfully registered rule %r"
msgstr ""

#: src/vigilo/correlator/registry.py:140
msgid ""
"Singleton has already been instanciated, ignoring attempt to create a new "
"instance."
msgstr ""

#: src/vigilo/correlator/registry.py:175
#, python-format
msgid "Not a valid rule name \"%s\""
msgstr ""

#: src/vigilo/correlator/registry.py:181
#, python-format
msgid "Unable to load rule \"%(name)s\" (%(class)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:115
msgid ""
"No information from Vigiconf concerning the topology's last modification "
"date. Therefore the topology has NOT been rebuilt."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:127
msgid "Topology has been reloaded."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:144
#, python-format
msgid "Sending this payload to the XMPP bus: %r"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:150
#, python-format
msgid ""
"Registering post-correlation callback function \"%(fn)s\" for alert with ID "
"%(id)s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:260
#, python-format
msgid "Rule %(rule_name)s timed out"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:322
#, python-format
msgid "Skipping unrecognized item (%s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:366
msgid ""
"Error while saving the correlated event. The message will be handled once "
"more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:381
msgid "Received invalid XMPP item ID (None)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:433
msgid ""
"Error while retrieving the network's topology. The message will be handled "
"once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:448
msgid ""
"Error while adding an entry in the HLS history. The message will be handled "
"once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:460
msgid ""
"Error while adding an entry in the history. The message will be handled once "
"more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:473
msgid "Error while saving state. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:495
#, python-format
msgid "Correlation failed for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:503
#, python-format
msgid "Unable to store correlated alert for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:550
msgid "Connection lost"
msgstr ""

#: src/vigilo/correlator/actors/rule_runner.py:82
#, python-format
msgid ""
"Got an exception while running rule %(rule)s. Running the correlator in the "
"foreground (%(prog)s -n) may help troubleshooting"
msgstr ""

#: src/vigilo/correlator/rules/example.py:36
#, python-format
msgid "id %(id)s payload %(payload)s"
msgstr ""

#: src/vigilo/correlator/test/test_logging.py:268
msgid "Received 'WARNING' message on lls1"
msgstr ""

#: src/vigilo/correlator/test/test_logging.py:289
msgid "Received 'CRITICAL' message on lls1"
msgstr ""

