# Translations template for vigilo-correlator.
# Copyright (C) 2011 ORGANIZATION
# This file is distributed under the same license as the vigilo-correlator
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-correlator 2.0.9\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2011-11-22 10:52+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_correlator.py:36
msgid "The topology has been reloaded."
msgstr ""

#: src/twisted/plugins/vigilo_correlator.py:53
msgid ""
"Could not set signal handlers. The correlator may not be able to shutdown "
"cleanly"
msgstr ""

#: src/vigilo/correlator/correvent.py:81
#, python-format
msgid ""
"Ignoring event #%(idevent)d on (%(host)r, %(service)r) as requested by the "
"correlation rules"
msgstr ""

#: src/vigilo/correlator/correvent.py:144
#, python-format
msgid ""
"Ignoring request to update correlated event %r: a more recent update already "
"exists in the database"
msgstr ""

#: src/vigilo/correlator/correvent.py:149
#, python-format
msgid "Updating existing correlated event (%r)"
msgstr ""

#: src/vigilo/correlator/correvent.py:152
#, python-format
msgid "Got a reference to a non-existent correlated event (%r), adding as new"
msgstr ""

#: src/vigilo/correlator/correvent.py:162
#, python-format
msgid "Raw event ignored. Reason: status = %r"
msgstr ""

#: src/vigilo/correlator/correvent.py:190
#, python-format
msgid ""
"Got a reference to a nonexistent correlated event (%r), skipping this "
"aggregate"
msgstr ""

#: src/vigilo/correlator/correvent.py:241
msgid "Creating new correlated event"
msgstr ""

#: src/vigilo/correlator/correvent.py:373
msgid "Sending correlated event to syslog"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:58
#, python-format
msgid "Received request to add an event on HLS \"%s\""
msgstr ""

#: src/vigilo/correlator/db_insertion.py:63
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), skipping "
"event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:95
#, python-format
msgid "Updating event %r"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:101
#, python-format
msgid ""
"Ignoring request to create a new event with state \"%s\" (nothing alarming "
"here)"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:108
msgid "Creating new event"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:111
msgid "Multiple matching events found, skipping."
msgstr ""

#: src/vigilo/correlator/db_insertion.py:161
#, python-format
msgid "Got a reference to a non configured high-level service (%(service)r)"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:188
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), skipping "
"state"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:253
#, python-format
msgid "Adding event #%(event)d (supitem #%(supitem)d) to aggregate #%(aggregate)d"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:272
#, python-format
msgid ""
"Event #%(event)d already belongs to aggregate #%(aggregate)d, refusing to add"
" it twice"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:303
#, python-format
msgid "Merging aggregate #%(src)d into aggregate #%(dest)d"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:355
#: src/vigilo/correlator/db_insertion.py:360
msgid "Got a reference to a nonexistent aggregate, aborting"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:372
#, python-format
msgid ""
"Event #%(event)d (supitem #%(supitem)d) will be merged into aggregate "
"#%(aggregate)d"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:35
#, python-format
msgid ""
"handle_ticket: Trouble ticket message received. Timestamp = %(timestamp)r. "
"Impacted HLS = %(hls)r. Ticket id = %(ticket_id)r. acknowledgement_status = "
"%(ack_status)r. Message = %(message)r."
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:57
#, python-format
msgid "handle_ticket: No matching trouble ticket found : %r"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:63
#, python-format
msgid "handle_ticket: Several events seem to be associated with this ticket : %r"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:66
#, python-format
msgid ""
"handle_ticket: The event %(event_id)r is associated with the given ticket "
"(%(ticket_id)r)"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:88
#, python-format
msgid "handle_ticket: Got exception while updating event %r history"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:92
#, python-format
msgid "handle_ticket: Event %r history updated successfully."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:62
#, python-format
msgid "Connected to memcached (%s)"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:79
#, python-format
msgid "Connecting to memcached server (%s)..."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:88
#, python-format
msgid "Connection to memcached (%(conn)s) lost: %(reason)s"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:101
#, python-format
msgid "Connection to memcached (%(conn)s) failed: %(reason)s"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:231
#, python-format
msgid "Trying to set value '%(value)s' for key '%(key)s' (transaction=%(txn)r)."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:274
#, python-format
msgid "Trying to get the value of the key '%(key)s' (transaction=%(txn)r)."
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:307
#, python-format
msgid "Trying to delete the key '%(key)s' (transaction=%(txn)r)."
msgstr ""

#: src/vigilo/correlator/registry.py:59
#, python-format
msgid ""
"Rule %(name)s (%(class)s) has already been registered, ignoring attempt to "
"re-register it."
msgstr ""

#: src/vigilo/correlator/registry.py:68
#, python-format
msgid "The rule %(depended)r must be loaded before %(dependent)r."
msgstr ""

#: src/vigilo/correlator/registry.py:77
#, python-format
msgid "Successfully registered rule %r"
msgstr ""

#: src/vigilo/correlator/registry.py:142
msgid ""
"Singleton has already been instanciated, ignoring attempt to create a new "
"instance."
msgstr ""

#: src/vigilo/correlator/registry.py:183
#, python-format
msgid "Not a valid rule name \"%s\""
msgstr ""

#: src/vigilo/correlator/registry.py:189
#, python-format
msgid "Unable to load rule \"%(name)s\" (%(class)s)"
msgstr ""

#: src/vigilo/correlator/actors/executor.py:85
#, python-format
msgid "Rule %(rule_name)s timed out"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:142
#, python-format
msgid "Unable to contact the database: %s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:187
#, python-format
msgid "Skipping unrecognized item (%s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:193
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:218
msgid "Received invalid XMPP item ID (None)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:232
msgid "Error while modifying the ticket"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:244
msgid "Error while retrieving supervised item ID"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:260
msgid ""
"The rule "
"'vigilo.correlator_enterprise.rules.hls_deps:HighLevelServiceDepsRule' must "
"be loaded for computation orders to be handled properly."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:270
#: src/vigilo/correlator/actors/rule_dispatcher.py:325
msgid "The connection to memcached timed out. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:345
msgid "Inserting state"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:347
msgid "Error while saving state"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:366
msgid "Inserting an entry in the HLS history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:368
msgid "Error while adding an entry in the HLS history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:373
msgid "Inserting an entry in the history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:375
msgid "Error while adding an entry in the history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:402
msgid "Actual correlation"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:438
#, python-format
msgid "Correlation process ended (%.4fs)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:458
msgid "Handling correlation results"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:482
#, python-format
msgid ""
"Error while saving the correlated event (%s). The message will be handled "
"once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:513
#, python-format
msgid "Correlation failed for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:534
#, python-format
msgid "Unable to store correlated alert for message #%(id)s (%(payload)s) : %(error)s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:558
msgid "Connection lost, stopping rule runners pool"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:598
#, python-format
msgid "%s. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_runner.py:36
#, python-format
msgid ""
"Got an exception while running rule \"%(rule)s\". Running the correlator in "
"the foreground (service vigilo-correlator debug) may help troubleshooting "
"(%(error)s)"
msgstr ""

#: src/vigilo/correlator/rules/SetPriority.py:102
#, python-format
msgid ""
"The priority for the alert on (%(hostname)r, %(servicename)r) is %(newprio)r "
"(old: %(oldprio)r)."
msgstr ""

#: src/vigilo/correlator/rules/example.py:36
#, python-format
msgid "id %(id)s payload %(payload)s"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:58
msgid "Host is down"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:60
#, python-format
msgid "Setting %d services to UNKNOWN"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:125
#, python-format
msgid "Unsupported transition: %(from)s -> %(to)s"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:135
#, python-format
msgid "Asking Nagios for updates on %d services"
msgstr ""

