# French translations for PACKAGE package
# Traductions françaises du paquet PACKAGE.
# Copyright (C) 2010 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Automatically generated, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version:  vigilo.corr\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-04-23 13:54+0200\n"
"PO-Revision-Date: 2011-08-31 12:09+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: fr <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_correlator.py:36
msgid "The topology has been reloaded."
msgstr "L'arbre topologique a été reconstruit."

#: src/twisted/plugins/vigilo_correlator.py:53
msgid ""
"Could not set signal handlers. The correlator may not be able to shutdown"
" cleanly"
msgstr ""
"Impossible d'installer le gestionnaire de signaux. Le corrélateur risque "
"de ne pas pouvoir être arrêté proprement"

#: src/vigilo/correlator/correvent.py:81
#, python-format
msgid ""
"Ignoring event #%(idevent)d on (%(host)r, %(service)r) as requested by "
"the correlation rules"
msgstr ""
"Événement #%(idevent)d sur (%(host)r, %(service)r) ignoré à la demande "
"des règles de corrélation"

#: src/vigilo/correlator/correvent.py:144
#, python-format
msgid ""
"Ignoring request to update correlated event %r: a more recent update "
"already exists in the database"
msgstr ""
"Demande de mise à jour de l'événement corrélé %r ignorée : une mise à "
"jour plus récente existe déjà dans la base de données"

#: src/vigilo/correlator/correvent.py:149
#, python-format
msgid "Updating existing correlated event (%r)"
msgstr "Mise à jour d'un événement corrélé existant (%r)"

#: src/vigilo/correlator/correvent.py:152
#, python-format
msgid "Got a reference to a non-existent correlated event (%r), adding as new"
msgstr ""
"L'événement corrélé référencé (%r) n'existe pas, il est donc ajouté à \"\n"
"\"la BDD."

#: src/vigilo/correlator/correvent.py:162
#, python-format
msgid "Raw event ignored. Reason: status = %r"
msgstr "Événement brut ignoré. Raison : statut = %r"

#: src/vigilo/correlator/correvent.py:190
#, python-format
msgid ""
"Got a reference to a nonexistent correlated event (%r), skipping this "
"aggregate"
msgstr "L'événement corrélé référencé (%r) n'existe pas, l'agrégat est ignoré."

#: src/vigilo/correlator/correvent.py:234
msgid "Creating new correlated event"
msgstr "Création d'un nouvel événement corrélé"

#: src/vigilo/correlator/correvent.py:346
msgid "Sending correlated event to syslog"
msgstr "Envoi de l'événement corrélé vers le syslog"

#: src/vigilo/correlator/db_insertion.py:56
#, python-format
msgid "Received request to add an event on HLS \"%s\""
msgstr "Réception d'une requête demandant l'ajout d'un événement sur le SHN \"%s\""

#: src/vigilo/correlator/db_insertion.py:61
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), "
"skipping event"
msgstr ""
"L'item référencé (%(host)r, %(service)r) n'existe pas, l'événement est "
"ignoré"

#: src/vigilo/correlator/db_insertion.py:93
#, python-format
msgid "Updating event %r"
msgstr "Mise à jour de l'événement %r"

#: src/vigilo/correlator/db_insertion.py:99
#, python-format
msgid ""
"Ignoring request to create a new event with state \"%s\" (nothing "
"alarming here)"
msgstr ""
"Demande de création d'un nouvel événement avec l'état \"%s\" ignorée "
"(rien d'alarmant)"

#: src/vigilo/correlator/db_insertion.py:106
msgid "Creating new event"
msgstr "Création d'un nouvel événement"

#: src/vigilo/correlator/db_insertion.py:109
msgid "Multiple matching events found, skipping."
msgstr "Plusieurs événements concernant l'item ont été trouvés, message ignoré."

#: src/vigilo/correlator/db_insertion.py:162
#, python-format
msgid "Got a reference to a non configured high-level service (%(service)r)"
msgstr "Le service de haut niveau référencé (%(service)r) n'existe pas"

#: src/vigilo/correlator/db_insertion.py:189
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), "
"skipping state"
msgstr ""
"L'élément référencé (%(host)r, %(service)r) n'existe pas, l'état est "
"ignoré"

#: src/vigilo/correlator/db_insertion.py:258
#, python-format
msgid "Merging aggregate #%(src)d with aggregate #%(dest)d"
msgstr "Fusion de l'agrégat #%(src)d avec l'éagrégat #%(dest)d"

#: src/vigilo/correlator/db_insertion.py:281
msgid "Got a reference to a nonexistent aggregate, aborting"
msgstr "L'agrégat référencé n'existe pas, abandon"

#: src/vigilo/correlator/handle_ticket.py:35
#, python-format
msgid ""
"handle_ticket: Trouble ticket message received. Timestamp = "
"%(timestamp)r. Impacted HLS = %(hls)r. Ticket id = %(ticket_id)r. "
"acknowledgement_status = %(ack_status)r. Message = %(message)r."
msgstr ""
"handle_ticket: Message reçu sur un ticket d'incident. Horodatage = "
"%(timestamp)r. SHN impacté = %(hls)r. ID ticket = %(ticket_id)r. état "
"d'acquittement = %(ack_status)r. Message = %(message)r."

#: src/vigilo/correlator/handle_ticket.py:57
#, python-format
msgid "handle_ticket: No matching trouble ticket found : %r"
msgstr "handle_ticket: Aucun ticket d'incident trouvé pour %r"

#: src/vigilo/correlator/handle_ticket.py:63
#, python-format
msgid "handle_ticket: Several events seem to be associated with this ticket : %r"
msgstr "handle_ticket: Plusieurs événements semblent associés à ce ticket : %r"

#: src/vigilo/correlator/handle_ticket.py:66
#, python-format
msgid ""
"handle_ticket: The event %(event_id)r is associated with the given ticket"
" (%(ticket_id)r)"
msgstr ""
"handle_ticket: L'événement %(event_id)r est associé au ticket indiqué "
"(%(ticket_id)r)"

#: src/vigilo/correlator/handle_ticket.py:88
#, python-format
msgid "handle_ticket: Got exception while updating event %r history"
msgstr ""
"handle_ticket: Une exception a été levée durant la mise à jour de "
"l'historique de l'événement %r"

#: src/vigilo/correlator/handle_ticket.py:92
#, python-format
msgid "handle_ticket: Event %r history updated successfully."
msgstr "handle_ticket: L'historique de l'évenement %r a bien été mis à jour"

#: src/vigilo/correlator/memcached_connection.py:68
#, fuzzy, python-format
msgid "Connected to memcached (%s)"
msgstr "Connexion au serveur memcached (%s) ..."

#: src/vigilo/correlator/memcached_connection.py:80
#, python-format
msgid "Connecting to memcached server (%s)..."
msgstr "Connexion au serveur memcached (%s) ..."

#: src/vigilo/correlator/memcached_connection.py:89
#, python-format
msgid "Connection to memcached (%(conn)s) lost: %(reason)s"
msgstr "Connexion à memcached (%(conn)s) perdue : %(reason)s"

#: src/vigilo/correlator/memcached_connection.py:102
#, python-format
msgid "Connection to memcached (%(conn)s) failed: %(reason)s"
msgstr "Échec de la connexion à memcached (%(conn)s) : %(reason)s"

#: src/vigilo/correlator/memcached_connection.py:205
#, python-format
msgid "Trying to set value '%(value)s' for key '%(key)s' (transaction=%(txn)r)."
msgstr ""
"Tentative d'affectation de la valeur '%(value)s' à la clé '%(key)s' "
"(transaction=%(txn)r)."

#: src/vigilo/correlator/memcached_connection.py:245
#, python-format
msgid "Trying to get the value of the key '%(key)s' (transaction=%(txn)r)."
msgstr ""
"Tentative de récupération de la valeur de la clé '%(key)s' "
"(transaction=%(txn)r)."

#: src/vigilo/correlator/memcached_connection.py:275
#, python-format
msgid "Trying to delete the key '%(key)s' (transaction=%(txn)r)."
msgstr "Tentative de suppression de la clé '%(key)s' (transaction=%(txn)r)."

#: src/vigilo/correlator/registry.py:58
#, python-format
msgid ""
"Rule %(name)s (%(class)s) has already been registered, ignoring attempt "
"to re-register it."
msgstr ""
"La règle %(name)s (%(class)s) a déjà été enregistrée, tentative de "
"ré-enregistrement ignorée."

#: src/vigilo/correlator/registry.py:67
#, python-format
msgid "The rule %(depended)r must be loaded before %(dependent)r."
msgstr "La règle %(depended)r doit être chargée avant  %(dependent)r."

#: src/vigilo/correlator/registry.py:75
#, python-format
msgid "Successfully registered rule %r"
msgstr "Enregistrement de la règle %r réussi"

#: src/vigilo/correlator/registry.py:140
msgid ""
"Singleton has already been instanciated, ignoring attempt to create a new"
" instance."
msgstr ""
"Le singleton a déjà été instancié, demande de création d'une nouvelle "
"instance ignorée."

#: src/vigilo/correlator/registry.py:175
#, python-format
msgid "Not a valid rule name \"%s\""
msgstr "Nom de règle non valide \"%s\""

#: src/vigilo/correlator/registry.py:181
#, python-format
msgid "Unable to load rule \"%(name)s\" (%(class)s)"
msgstr "Impossible de charger la règle \"%(name)s\" (%(class)s)"

#: src/vigilo/correlator/actors/executor.py:78
#, python-format
msgid "Rule %(rule_name)s timed out"
msgstr "La règle %(rule_name)s a dépassé le délai d'exécution"

#: src/vigilo/correlator/actors/rule_dispatcher.py:150
#, python-format
msgid "Unable to contact the database: %s"
msgstr "Impossible de contacter la base de données : %s"

#: src/vigilo/correlator/actors/rule_dispatcher.py:186
#, python-format
msgid "Skipping unrecognized item (%s)"
msgstr "Élément non-reconnu ignoré (%s)"

#: src/vigilo/correlator/actors/rule_dispatcher.py:216
msgid "Received invalid XMPP item ID (None)"
msgstr "Réception d'un ID XMPP non valide (None)"

#: src/vigilo/correlator/actors/rule_dispatcher.py:225
#, fuzzy
msgid "Error while modifying the ticket"
msgstr "Erreur lors de la modification du ticket"

#: src/vigilo/correlator/actors/rule_dispatcher.py:237
msgid "Error while retrieving supervised item ID"
msgstr "Erreur lors de la récupération de l'ID de l'élément supervisé"

#: src/vigilo/correlator/actors/rule_dispatcher.py:271
#, python-format
msgid "Error: %s"
msgstr "Erreur : %s"

#: src/vigilo/correlator/actors/rule_dispatcher.py:288
msgid "Inserting state"
msgstr "Insertion de l'état"

#: src/vigilo/correlator/actors/rule_dispatcher.py:290
msgid "Error while saving state"
msgstr "Erreur lors de la sauvegarde de l'état"

#: src/vigilo/correlator/actors/rule_dispatcher.py:309
msgid "Inserting an entry in the HLS history"
msgstr "Ajout d'une entrée dans l'historique des SHN"

#: src/vigilo/correlator/actors/rule_dispatcher.py:311
msgid "Error while adding an entry in the HLS history"
msgstr "Erreur à l'ajout d'une entrée dans l'historique des SHN"

#: src/vigilo/correlator/actors/rule_dispatcher.py:316
msgid "Inserting an entry in the history"
msgstr "Ajout d'une entrée dans l'historique"

#: src/vigilo/correlator/actors/rule_dispatcher.py:318
msgid "Error while adding an entry in the history"
msgstr "Erreur à l'ajout d'une entrée dans l'historique"

#: src/vigilo/correlator/actors/rule_dispatcher.py:328
msgid "Actual correlation"
msgstr "Lancement de la corrélation"

#: src/vigilo/correlator/actors/rule_dispatcher.py:359
#, python-format
msgid "Correlation process ended (%.4fs)"
msgstr "Le processus de corrélation se termine (%.4fs)"

#: src/vigilo/correlator/actors/rule_dispatcher.py:379
msgid "Handling correlation results"
msgstr "Traitement des résultats de la corrélation"

#: src/vigilo/correlator/actors/rule_dispatcher.py:403
#, python-format
msgid ""
"Error while saving the correlated event (%s). The message will be handled"
" once more."
msgstr ""
"Erreur lors de l'enregistrement de l'événement corrélé (%s). \"\n"
"\"Le message sera traité à nouveau."

#: src/vigilo/correlator/actors/rule_dispatcher.py:434
#, python-format
msgid "Correlation failed for message #%(id)s (%(payload)s)"
msgstr "La corrélation a échoué pour le message #%(id)s (%(payload)s)"

#: src/vigilo/correlator/actors/rule_dispatcher.py:455
#, python-format
msgid ""
"Unable to store correlated alert for message #%(id)s (%(payload)s) : "
"%(error)s"
msgstr ""
"Impossible de sauvegarder l'alerte corrélée pour le message #%(id)s "
"(%(payload)s) : %(error)s"

#: src/vigilo/correlator/actors/rule_dispatcher.py:479
msgid "Connection lost"
msgstr "Connexion perdue"

#: src/vigilo/correlator/actors/rule_dispatcher.py:528
#, python-format
msgid "%s. The message will be handled once more."
msgstr "%s. Le message sera traité à nouveau."

#: src/vigilo/correlator/actors/rule_dispatcher.py:533
#, python-format
msgid "Unexpected error: %s"
msgstr "Erreur inattendue : %s"

#: src/vigilo/correlator/actors/rule_runner.py:85
#, python-format
msgid ""
"Got an exception while running rule %(rule)s. Running the correlator in "
"the foreground (%(prog)s -n) may help troubleshooting"
msgstr ""
"Exception levée pendant la règle %(rule)s. Lancer le corrélateur au "
"premier plan (%(prog)s -n) peut aider à déboguer"

#: src/vigilo/correlator/amp/correlator.py:20
#, python-format
msgid "Sending this payload to the XMPP bus: %r"
msgstr "Envoi de ce message sur le bus XMPP : %r"

#: src/vigilo/correlator/amp/correlator.py:26
#, python-format
msgid ""
"Registering post-correlation callback function \"%(fn)s\" for alert with "
"ID %(id)s"
msgstr ""
"Enregistrement de la fonction de rappel post-corrélation \"%(fn)s\" pour "
"l'alerte dont l'ID est %(id)s"

#: src/vigilo/correlator/rules/example.py:38
#, python-format
msgid "id %(id)s payload %(payload)s"
msgstr "id %(id)s message %(payload)s"

#: src/vigilo/correlator/rules/svc_on_host_down.py:62
msgid "Host is down"
msgstr "L'hôte est DOWN"

#: src/vigilo/correlator/rules/svc_on_host_down.py:64
#, python-format
msgid "Setting %d services to UNKNOWN"
msgstr "Passage de %d services à l'état UNKNOWN"

#: src/vigilo/correlator/rules/svc_on_host_down.py:133
#, python-format
msgid "Unsupported transition: %(from)s -> %(to)s"
msgstr "Transition non supportée : %(from)s -> %(to)s"

#: src/vigilo/correlator/rules/svc_on_host_down.py:144
#, python-format
msgid "Asking Nagios for updates on %d services"
msgstr "Demande de mise à jour de Nagios concernant %d services"

